export const ROTATING_WEBSITES = [
  "acmvit.in",
  "code2create.acmvit.in",
  "examcooker.acmvit.in",
  "",
];

export const IFRAME_WHITELIST = new Set([
  "os.acmvit.in",
  "localhost.acmvit.in",
  "rcpc.acmvit.in",
  "codeplusplus.acmvit.in",
  "acmvit.in",
  "fast.com",
  "icpc.global",
  //"comick.live",

  "slither.io",
  "krunker.io",
  "diep.io",
  "splix.io",
  "skribbl.io",
  "1v1.lol",
  "ev.io",
  "shellshock.io",
  "bonk.io",
  "littlealchemy2.com",
  "zombs.io",
  "surviv.io",
  "classic.minecraft.net",
  "2048game.com",
  "lichess.org",
  "worldsbiggestpacman.com",
  "snowrider3d.com",
  "slopegame.online",
  "tetr.io",
  "wanderers.io",
  "wormate.io",

  "codepen.io",
  "jsfiddle.net",
  "codesandbox.io",
  "replit.com",
  "stackblitz.com",
  "glitch.me",
  "threejs.org",
  "p5js.org",
  "openprocessing.org",
  "codewars.com",
  "leetcode.com",
  "geeksforgeeks.org",
  "uiverse.io",
  "regex101.com",
  "jwt.io",
  "jsonlint.com",
  "httpbin.org",
  "reqres.in",
  "mocky.io",
  "codebeautify.org",
  "pastebin.com",
  "stackedit.io",
  "hackmd.io",
  "markdownlivepreview.com",
  "mdn.dev",
  "w3schools.com",
  "jsdelivr.net",
  "unpkg.com",
  "cdnjs.com",
  "raw.githack.com",
  "pythonanywhere.com",
  "vercel.app",
  "netlify.app",
  "herokuapp.com",
  "repl.co",
  "surge.sh",
  "firebaseapp.com",
  "supabase.com",
  "render.com",

  "tldraw.com",
  "excalidraw.com",
  "miro.com",
  "figma.com",
  "canva.com",
  "draw.io",
  "diagrams.net",
  "vectr.com",
  "pixlr.com",
  "photopea.com",
  "sketch.io",
  "jspaint.app",
  "flipanim.com",
  "autodraw.com",
  "pixilart.com",
  "jamboard.google.com",

  "openstreetmap.org",
  "geojson.io",
  "earth.google.com",
  "maps.google.com",
  "maptiler.com",
  "bing.com/maps",
  "wego.here.com",
  "leafletjs.com",
  "mapbox.com",
  "nasa.gov",
  "stellarium-web.org",
  "peakfinder.org",

  "docs.google.com/forms",
  "docs.google.com/presentation",
  "docs.google.com/spreadsheets",
  "drive.google.com/file",
  "calendar.google.com/calendar",
  "youtube.com/embed",
  "player.vimeo.com",

  "open.spotify.com/embed",
  "soundcloud.com",
  "bandcamp.com",
  "radio.garden",
  "tunein.com",
  "anchor.fm",

  "archive.org",
  "openlibrary.org",
  "britannica.com",

  "c2c.acmvit.in",
  "cryptichunt.acmvit.in",
  "examcooker.acmvit.in",
  "unipool.acmvit.in",
  "cli-rpg.acmvit.in",

  "neetcode.io",
  "cses.fi",
  "algomap.io",
]);

export const INTERNAL_KEYWORDS = new Set([
  "instructions",
  "cc",
  "management",
  "tech",
  "design",
  "research",
  "events",
  "domains",
  // "pintoorun",
  "snake",
  "about",
]);

export const BOOKMARK_LABELS: Record<string, string> = {
  instructions: "Instructions",
  cc: "CC",
  management: "Management",
  tech: "Tech",
  design: "Design",
  research: "Research",
  events: "Events",
  domains: "Domains",
  // pintoorun: "PintooRun",
  snake: "Snake",
  about: "About",
};
